ifndef::imagesdir[:imagesdir: ../images]

[[section-technical-risks]]
== Risiken und technische Schulden

=== Limitationen des Datenmodells

Das Datenmodell bildet bisher folgende Dinge nicht ab 

* mehrere Bestelladressen eines Kunden (erfordert weitere Tabelle)
* Zustand eines Exemplars (erfordert weiteres Feld in Exemplartabelle)

Das System prüft nicht, ob es "konkurrierende Leihen" gibt, d.h. ob ein Exemplar gleichzeitig von zwei Kunden ausgeliehen wird.

Die Namen der Autoren sind im Quellsystem nicht nach Vor- und Nachname getrennt. 
Eine korrekte automatische Trennung im ETL-Prozess ist aufgrund verschiedener Namensformate (mehrere Nachnamen; Zusätze wie de, von, van; Nachname Vorname) sehr schwierig umsetzbar. Eine Anpassung im Quellsystem wird empfohlen.

ifdef::arc42help[]
[role="arc42help"]
****
.Inhalt
Eine nach Prioritäten geordnete Liste der erkannten Architekturrisiken und/oder technischen Schulden.

.Motivation
"Risikomanagement ist Projektmanagement für Erwachsene."
-- Tim Lister, Atlantic Systems Guild

Unter diesem Motto sollten Sie Architekturrisiken und/oder technische Schulden gezielt ermitteln, bewerten und Ihren Management-Stakeholdern (z.B. Projektleitung, Product-Owner) transparent machen.

.Form
Liste oder Tabelle von Risiken und/oder technischen Schulden, eventuell mit vorgeschlagenen Maßnahmen zur Risikovermeidung, Risikominimierung oder dem Abbau der technischen Schulden.


.Weiterführende Informationen

Siehe https://docs.arc42.org/section-11/[Risiken und technische Schulden] in der online-Dokumentation (auf Englisch!).
****
endif::arc42help[]
